### ISSUE TITLE
build frequency pattern

### ISSUE THREAD

**Issue by ransur0t** [jacobalberty/unifi-docker#104]
Hi,

This submission is more of any inquiry than an issue.  Foremost, thank you for the excellent builds and timely updates.  I'm running the UniFi controller on a Debian 8 openmediavault NAS using the 'stable' tag.  I also use the watchtower docker image to monitor containers and update them when new builds are available.  Since there have been several successive builds published over the last couple days, yet no new UniFi stable version update, I'm curious what dictates your build frequency pattern?

There has not been any negative impact to the container updates, I am just curious about your method!

Thanks,

**Comment by jacobalberty** [comment]
There have been several beta builds, including several stable candidate
betas. I don't build off those instead there's the beta tag you can supply
a pkgurl to and it will build them. As soon as it hits the unifi update
blog I build it and tag it out. Might take me a few hours if I'm not home
when it happens but in general it should be available within a day of it
going on the update blog.

On Feb 17, 2018 4:36 PM, "ransur0t" <notifications@github.com> wrote:

Hi,

This submission is more of any inquiry than an issue. Foremost, thank you
for the excellent builds and timely updates. I'm running the UniFi
controller on a Debian 8 openmediavault NAS using the 'stable' tag. I also
use the watchtower docker image to monitor containers and update them when
new builds are available. Since there have been several successive builds
published over the last couple days, yet no new UniFi stable version
update, I'm curious what dictates your build frequency pattern?

There has not been any negative impact to the container updates, I am just
curious about your method!

Thanks,

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jacobalberty/unifi-docker/issues/104>, or mute the
thread

**Comment by ransur0t** [comment]
I follow the Unifi update blog as well, and have noticed the recent updates to the stable candidate version.  I guess my question, more specifically, is why have there been new builds for stable, when the controller release version is still 5.6.30?

Please bear in mind that I am unfamiliar with the mechanisms of the docker build system ...

Thanks,

**Comment by jacobalberty** [comment]
Ah I tag stable candidates out on their own tag. Use the version with -sc
on the end I think it's 5.6.35-sc for the latest 5.6.x sc. I list the tags
in README.md for the latest versions

**Comment by ransur0t** [comment]
Yes, I understand your tagging system.  What's puzzling me is that stable tag has received multiple new builds over the past few days, but the controller version has not changed.  Do you rebuild all images/tags when any one version/tag requires a new build?

**Comment by jacobalberty** [comment]
According to the unifi updates blog there hasn't been a new stable in 3
weeks which was 5.6.30. there have been two stable candidates within the
past week. I tagged both of those out already as stable candidates. When
they hit stable (should be a week after they were released as candidates)
I'll tag them out as their respective releases (stable and oldstable iirc)

On Feb 17, 2018 5:18 PM, "ransur0t" <notifications@github.com> wrote:

Yes, I understand your tagging system. What's puzzling me is that stable
tag has received multiple new builds over the past few days, but the
controller version has not changed. Do you rebuild all images/tags when any
one version/tag requires a new build?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jacobalberty/unifi-docker/issues/104#issuecomment-366478731>,
or mute the thread

**Comment by jacobalberty** [comment]
Ohh you mean the stable tag on the hub has been updated. I'm sorry I
misunderstood. Yes to update readme.md I must rebuild the 'latest' tag
which is also stable

On Feb 17, 2018 5:27 PM, jacob.alberty@gmail.com wrote:

According to the unifi updates blog there hasn't been a new stable in 3
weeks which was 5.6.30. there have been two stable candidates within the
past week. I tagged both of those out already as stable candidates. When
they hit stable (should be a week after they were released as candidates)
I'll tag them out as their respective releases (stable and oldstable iirc)

On Feb 17, 2018 5:18 PM, "ransur0t" <notifications@github.com> wrote:

Yes, I understand your tagging system. What's puzzling me is that stable
tag has received multiple new builds over the past few days, but the
controller version has not changed. Do you rebuild all images/tags when any
one version/tag requires a new build?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jacobalberty/unifi-docker/issues/104#issuecomment-366478731>,
or mute the thread

**Comment by ransur0t** [comment]
Yup, that's what I was getting at, and that handles my inquiry and explains the behavior of updated builds of stable/latest!

Thanks, I appreciate your timely replies and commitment to providing UniFi controller docker images.
