### ISSUE TITLE
Two log folders

### ISSUE THREAD

**Issue by maforshaw** [jacobalberty/unifi-docker#113]
I just upgraded to the latest stable version and had a java crash due to a missing folder. It looks like "server.log" has moved from "/unifi/log/server.log" to "/unifi/logs/server.log" even though the environment variable LOGDIR is set to "/unifi/log".

In fact, from a clean install there now appears to be 2 log folders:

/unifi/log
/unifi/logs

**Comment by jacobalberty** [comment]
I've dug and  dug trying to find where /unifi/logs is getting set, the only thing i can figure is for server.log it's using something like {unifi.datadir}/../logs or using {cwd}/logs and just ignoring unifi.logdir, I may tend up just having to move all the logs to /unifi/logs instead of /unifi/log but i was trying to maintain something similar to the /var structure

**Comment by maforshaw** [comment]
Whatever is creating server.log is creating it with root permissions. Even when I created the logs folder it still failed because of this. I run the docker container with the UID/GID environment variables set to 999 so had to manually change the root permissions that had been set on server.log to 999 to allow access.

**Comment by jacobalberty** [comment]
Somehow I missed the pull request #114 from @jandubois that fixes this, I've merged it into the beta branch now. Working on verifying it then merging it out to the rest of the branches.

**Comment by jacobalberty** [comment]
PR #114 was merged and fixes this.
