### ISSUE TITLE
OpenJDK 64-bit Server Warning

### ISSUE THREAD

**Issue by victoere** [jacobalberty/unifi-docker#2]
When I install the docker I get the following in the console log
_OpenJDK 64-bit Server Warning : You have loaded library /usr/lib/unifi/native/Linux/amd64/libubnt_webrtc_jni.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It is highly recommended that you fix the library with 'execstack -c <libfile>, or link it with 'noexecstack'_

I do get a URL that shows:
_HTTP status 400
description: The request sent by the client was syntactically incorrect._

I'm trying to load this in container station for QNAP.

**Comment by pengtuck** [comment]
I don't think the AP is even running at this point. Not sure how to fix it yet unless to force it to run as 32-bit ?

**Comment by MikeSchroll** [comment]
FWIW, I also receive this error; but it doesn't seem to impact functionality.

**Comment by MikeSchroll** [comment]
I was successful in resolving this error with:
docker exec -it unifi-brm1 /bin/bash -c "apt-get update && apt-get install execstack && execstack -c /usr/lib/unifi/lib/native/Linux/amd64/libubnt_webrtc_jni.so"

This could be integrated into the Dockerfile. Though I don't exactly understand what its doing, why, and if its necessary. I just did what it said to remove the warning.

**Comment by jacobalberty** [comment]
Looks like its a bug in unifi itself though, does the issue occur using a native install of unifi outside of docker? May want to report it directly to ubiquiti if so

**Comment by phroggster** [comment]
> ... does the issue occur using a native install of unifi outside of docker?

Yes, this occurs outside of a containerized deployment model.

> Though I don't exactly understand what its doing, why, and if its necessary.

OpenJDK is warning us that libubnt_webrtc_jni.so was not explicitly compiled with/without support for non-executable stack, a form of [protection](https://en.wikipedia.org/wiki/Executable_space_protection) akin to DEP. Since OpenJDK is unsure of whether or not the protection is already there, it's going to wrap library calls with canaries in order to try and notice and respond to certain very bad things. Running `execstack -c` marks this library file, on-disk, with stack protection. Anytime the library gets loaded thereafter, it will automatically have the NX (NoeXecute) flag set for stack memory, and the loader doesn't even have to do additional work.

Not sure why I can't hide the incorrect db97d4d commit from this view, but a08ca29 addresses this until such time as Ubiquiti releases an update. If you'd like a PR for this in the meantime, let me know.

**Comment by jacobalberty** [comment]
I'm just curious, does this still issue still occur with the latest images running openjdk 8 for you guys?

**Comment by phroggster** [comment]
Just updated a container and ran it through the webRTC/cloud connectivity ringer. Haven't seen any spurious logs as of yet.

**Comment by pengtuck** [comment]
I retested this on qnap with a reinstall. No error logs showing up
