### ISSUE TITLE
Switch to Alpine Linux

### ISSUE THREAD

**Issue by denisvm** [jacobalberty/unifi-docker#22]
It might be a good idea to switch to Alpine Linux to decrease the image size. There might 

There's an official image openjdk:8-jdk-alpine available now, and mongodb package on testing branch of Alpine.

Although it would be better if Ubiquiti offered an official package for Alpine.

**Comment by jacobalberty** [comment]
I'll look at using alpine as an alternative to the main image but there's a couple points to sticking with debian.

#1 Debian is more or less the "officially supported" option from Ubiquiti. by using debian we stick closer to their supported linux configuration.

#2 the debian:jessie is a common base image for many other images, once you've got debian:jessie downloaded once then pulling unifi only pulls the changes from jessie to unifi which leads to the third one.

#3 I'm not sure that the alpine image will be smaller by much. 500mb of the unifi image is all unifi and its dependencies, maybe the alpine image will somehow be smaller by pulling fewer dependencies? But that means something will likely be broken. It's also possible the debian dependencies are just bigger than the alpine ones due to including documentation. In that case though I can probably shrink the debian images by deleting any documentation that gets pulled in during the build.

All in all though if I can get an alpine image based on openjdk:8-jdk-alpine going without too much trouble I'm happy to add it as an extra tag.
