### ISSUE TITLE
HTTP Status 400 – Bad Request

### ISSUE THREAD

**Issue by mniesiobedzki** [jacobalberty/unifi-docker#224]
### Host operating system
Docker on Synology

### What tag are you using
`stable`

### What do you expect to happen?
Open in browser - HTTP on port 8880 (or HTTPS on port 8843).
After successful open a HTTP I would like to use HA proxy to redirect from HTTPS from internet, to local HTTP.

### What actually happens?
"HTTP Status 400 – Bad Request" instead of Web UI. I would like to use HTTP instead of HTTPS. Port 8443 is accessible - Web UI works.

**Comment by ssbarnea** [comment]
I am facing the same issue where I get 400 on 8843 port which is supposed to serve the portal page.

I suspect it has to do with SSL certificates, probably the server fails to load them or something similar.

Funny remark, I happen to want to use it in the same setup, where haproxy is offloading the SSL part out of the unifi-docker container. I do not even need to deploy a certificate on the container because haproxy will serve the correct one. Still, the container still gives 400.

**Comment by martinezpenya** [comment]
I'm getting error 400: Bad request... but only accessing bottom-left icon (settings), all the others work well.
From android APP settings is working but with its obvious limitations.

**Comment by poltrian** [comment]
Is there any solution? same here with the lastest container
