### ISSUE TITLE
New Firmware notification?

### ISSUE THREAD

**Issue by zeular** [jacobalberty/unifi-docker#240]
Is it possible to receive notifications in the Controller when there is a new firmware update? As it is when running the windows version? (Just to keep track of new updates.)

**Comment by nxadm** [comment]
The controller on the container shows a pop-up when new versions are available.

**Comment by zeular** [comment]
I have never received any notification when it is a new Firmware for the controller. (I mean in the UniFi controller.) I have received notifications when there have been updates for AP's. 
When I press "check latest firmware", (in settings/maintenance,) I only get that I already have the latest version...

**Comment by nxadm** [comment]
I just noticed it recently, while running a very recent older version of the docker image and got a pop-up to upgrade to the latest. This is a feature of the controller software and not the image/container. Of course, if you upgrade often to the latest image you won't see it because the controller will be up to date. To test it, you could run an older image (e.g. on alternative ports) and check if a new controller version is proposed.
