### ISSUE TITLE
HTTP 500 when accessing UI via reverse proxy

### ISSUE THREAD

**Issue by rschoenbichler** [jacobalberty/unifi-docker#264]
### Host operating system

Fedora 31

### What tag are you using

latest

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

`podman create \
        --name unifi-controller \
        -d \
        -p 192.168.0.1:3478:3478/udp \
        -p 192.168.0.1:6789:6789/tcp \
        -p 8443:8443/tcp \
        -p 192.168.0.1:8880:8880/tcp \
        -p 192.168.0.1:8080:8080/tcp \
        -p 192.168.0.1:8843:8843/tcp \
        -p 192.168.0.1:10001:10001/udp \
        -v /opt/unifi/data:/unifi:Z \
        -e RUNAS_UID0=false \
        jacobalberty/unifi:latest`

Additionally, I'm exposing the 8443 port via reverse proxy (traefik 2.0).
 
### What do you expect to happen?

I would expect to be able to connect to the controller over the reverse proxy URL.

### What actually happens?
The controller is working fine. Devices are registered and I can access it via the internal 192.168.0.1:8443 address. However, according to chrome, the SSL certificate is invalid.

When accessing via reverse proxy, I'm seeing a HTTP 500 internal server error. Unfortunately, there is no further log information available (neither in the response nor in the podman logs).
One possible issue I can see here is the invalid certificate, that might causes traefik to return the error.

Any ideas on how to resolve this would be appreciated!

Personally, I think the controller UI should only operate on port 80 (instead of 8880, 8843 and 8443), allowing composition with reverse proxies and SSL management in existing environments.

**Comment by mkilchhofer** [comment]
This works as the guys from ubnt designed the architecture.
The UI uses port 8443. Every other port just answers with a redirection to 8443.
The devices (switches, APs, etc.) talk to the API running on port 8080 (http://unifi:8080/inform by default).

I run the unifi controller inside kubernetes and wanted to expose the UI via an Ingress reverse proxy (Traefik 1.7) to my workstations subnet to have a simply way for using Let's encrypt certificates.

With this setup I also experienced this behavior unless I configured traefik with this:
```toml
[serversTransport]
  insecureSkipVerify = true
```

This is because unifi uses self signed certs which traefik simply does not trust.

**Comment by rschoenbichler** [comment]
Thanks for the update, I also found this [post](https://community.containo.us/t/traefik-v2-and-unifi-controller/3231) which points in the same direction.
I'll close this for now.
Still I think it would be better to expose the UI over HTTP only and not rely on self signed certificates. Instead you could easily apply SSL encryption on top i.e. via reverse proxy.

**Comment by darkhelmet** [comment]
@mkilchhofer I'm almost crying I'm so happy I found your comment. Solves my problem.
