### ISSUE TITLE
Entrypoint must not assume setuid is possible

### ISSUE THREAD

**Issue by jtackaberry** [jacobalberty/unifi-docker#279]
This isn't actually a problem right now, but this issue is more of a reaction to the README comment about running as a non-root user, where you say:

> At some point in the future this feature may default to on and I personally run all of my own containers with it on.

I just want to convince you not to make it mandatory even if you make it default, in case you had ideas of making the use of `gosu` the only behavior supported.

If a container is able to drop privileges via `setuid()`/`seteuid()` then it means it's running as root to begin with.  However, the better way to run a container as non-root is to do so via the container runtime, such as by passing `--user` to docker or using a `runAsUser` securityContext in a Kubernetes pod (as I'm doing).  In this case, the entrypoint runs as nonroot, and so `usermod`/`groupmod`/`gosu` as currently in `docker-entrypoint.sh` will fail.

Container images shouldn't force operators to run as root merely for the benefit of being able to then immediately drop privileges within the container.  They should at least support the configuration where the container is instantiated from the beginning as non-root.

Thanks for listening. :)

**Comment by jacobalberty** [comment]
I hadn't planned to make it mandatory.

The reason I haven't yet though is permission related, grabbing low ports is still iffy with docker and I can't reliably drop root privilege and grab low ports.

`gosu` is used right now because I change privileges of the executable to give it the capability to grab low ports. This is unreliable because a) it won't work if `--user` is used to drop privileges and b) it may fail depending on the filesystem/host os.

I'm hopeful that the linux kernel will get some improvements to allow docker to pass the capability directly instead of the hack I'm using now. I revisit it every year or so to see if things have improved. When I do make non-root the default it will be because the capabilities api in the kernel and in docker have aligned enough that there's a better solution than the hack in place now.

**Comment by jtackaberry** [comment]
Thanks Jacob for the insight.  True that's a bit of of worms, but isn't Unifi binding exclusively to high ports?
