### ISSUE TITLE
When latest Tag will point to V6.x

### ISSUE THREAD

**Issue by DannMendis** [jacobalberty/unifi-docker#358]
### Host operating system

Example: `Debian stretch` or `Open Media Vault 3`

### What tag are you using

Example: `stable`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

Example: `docker run --rm --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='Africa/Johannesburg' -v ~/unifi/data:/var/lib/unifi -v ~/unifi/logs:/var/log/unifi --name unifi jacobalberty/unifi:unifi5`

Note: A screenshot of your configuration page if using a gui is acceptable

**Comment by DannMendis** [comment]
Just want to check When latest Tag will point to V6.x. Thanks for this fantastic docker image.

**Comment by rogierlommers** [comment]
Same question here; also wondering how this upgrade will look like. No need to migrate stuff?

**Comment by coalfield** [comment]
+1 here 👍

**Comment by jacobalberty** [comment]
so 6.0.24 had some notes that indicate that it fixes most of the vlan issues, 6.0.26 just got pushed to public rc about 7 hours ago (and 6.0.24 apparently never made it out of rc). I'm thinking 6.0.26 is probably a good point to move  latest to point to the 6.0.x series, especially with 6.1.x now hitting beta.

**Comment by reibuehl** [comment]
In the README you state "This is your grace period to either upgrade to 6.0.x manually and ensure nothing breaks". Could you please add some documentation / guidelines how to do such a manual upgrade before you switch latest to 6.x?

**Comment by jacobalberty** [comment]
@reibuehl there isn't a whole lot to do to manually upgrade, you would backup, and tell whatever docker management system you're using to use `jacobalberty/docker:stable-6` instead of just `jacobalberty/docker:latest`, the backup should be part of any unifi upgrade already ( in fact unifi already puts a backup in `/unifi/data/backup` at every upgrade) and the image change is going to vary based on what platform you're hosting docker on.

**Comment by jacobalberty** [comment]
pr #369 being merged closes this.
