### ISSUE TITLE
Update docker to latest 6 on synology

### ISSUE THREAD

**Issue by ThaCeeBee** [jacobalberty/unifi-docker#368]
Hello,

I am using the 5.14.23 docker image in my synology docker. I would like to update tot the latest 6 release, but I do not know how.
Normally to update I download the "latest" image and stop the docker, then erase (not delete) the docker and restart it.
Can you, or anybody, please tell me how to update to latest 6?

Many thanks!

**Comment by jacobalberty** [comment]
There are currently some AP vlan issues with 6.0.23 so for now to try and limit how many people using watchtower get pushed to 6.0.23 and break their setups I've put 6 under the tag `stable-6`.

There has been a few RC releases that seem to fix the issues but none of them have hit https://www.ui.com/download/unifi/ yet indicating they're stable. Once one of the newer ones with the vlan fixes gets to that page I will move `latest` to the unifi 6 releases. That will also give users time to move to `stable-5` if they aren't ready to upgrade to 6 yet.

**Comment by ThaCeeBee** [comment]
Many thanks for this.

**Comment by it-can** [comment]
6,0.28 is official now

https://community.ui.com/releases/UniFi-Network-Controller-6-0-28/23c77a99-0957-449a-b3c0-58a37d4df81f

**Comment by eduardonit** [comment]
> There are currently some AP vlan issues with 6.0.23 so for now to try and limit how many people using watchtower get pushed to 6.0.23 and break their setups I've put 6 under the tag `stable-6`.

@jacobalberty  You're right, I use watchover on my NAS Synology and my controller are not working now. Im getting a message that said _"UniFi Controller startup failed. We do not support upgrading from 6.0.23._ So I was wondering if this is a related issue because I was using unifi:latest tag, And you mention in the description that the latest tag is using the latest 5.x version, not 6.x. So I'm confused. Any workaround you can suggest to me to fix this? thanks in advance

**Comment by jacobalberty** [comment]
@eduardonit that's related to #364

**Comment by jacobalberty** [comment]
the `latest` tag is now on 6.0.28 now that #369  was merged
