### ISSUE TITLE
docker hub info out of date

### ISSUE THREAD

**Issue by myster-t** [jacobalberty/unifi-docker#379]
just notifying you guys that https://registry.hub.docker.com/r/jacobalberty/unifi/ is out of date. had to find new information by coming to github. for instance, `latest` points to 6.0.x since oct 20.

**Comment by jacobalberty** [comment]
So now that I've moved to building via travis-ci instead of on the hub that is no longer synced to README.md like it was. I am for now manually updating it. I would like to use something like https://github.com/peter-evans/dockerhub-description but it's inherently incompatible with 2fa at the moment as the docker api [does not support updating that using a personal access token](https://github.com/docker/hub-feedback#1927) There is a roadmap entry (docker/roadmap#115) for it that I'm watching and if it ever gets implemented I'll go ahead and set up that github action for it.
