### ISSUE TITLE
Port 10001 missing for Synology Docker deployment

### ISSUE THREAD

**Issue by LexxM3** [jacobalberty/unifi-docker#421]
### Host operating system

Synology DSM 6.2.3-25426 Update 3
Synology Docker Package 18.09.0-0515

### What tag are you using

latest

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

See screen cap of partial relevant config:

![UniFi_Controller_Docker_on_Synology_20210917_01](https://user-images.githubusercontent.com/55937877/111414967-5baaf600-86b7-11eb-9d42-5daa456801a8.PNG)

### What do you expect to happen?

Port 10001 to be included in the list of used ports.

### What actually happens?

Port 10001 is not listed and is, therefore, typically not configured resulting in inability of UniFi Controller to adopt new devices (port 10001 is the discovery service).

### Mitigation or Workaround

Manually add port 10001.

**Comment by LexxM3** [comment]
The issue still exists as of 15-Dec-2021.  A bot closing a real issue because devs don't care enough to look at it doesn't make it a non-issue and should not be closed as a process.

**Comment by jacobalberty** [comment]
If you run in host mod or macvlan those ports don't do anything, all ports
are open by default in those two modes. If you run in bridged mode you need
a l3 adoption strategy because docker blocks broadcast traffic of all types
from crossing the bridge and port 10001 is used for broadcast traffic see
this link:
https://community.ui.com/questions/UDP-broadcasts-on-port-10001/1a81e0fe-203e-43e1-9c8b-d24e6d905c85
where support explains that's for broadcast traffic. For l3 adoption these
are the ports needed.
https://help.ui.com/hc/en-us/articles/218506997-UniFi-Ports-Used#2

Port 10001 needs no further configuration for any adoption strategies it's
relevant for

**Comment by LexxM3** [comment]
The default Synology configuration (as demonstrated in pretty much every easy to find tutorial) is bridged mode and therefore the Dockerfile as is fails to fully configure the instance and caused a rather a lot of frustration.  Note that majority of users setting up a Synology install are likely relative UniFi amateurs without much tribal knowledge.  Your own link relating to L3 adoption specifically references port 10001 as required for device discovery.  Every Synology tutorial referencing this distribution also indicates opening 10001 on the Synology firewall.  I don't understand the objection, although it is possible that is due to lack of the previously mentioned arcane tribal UniFi knowledge.

**Comment by jacobalberty** [comment]
That link says port 10001 is for l2 discovery. That's why it's not in the
l3 ingress ports list. Adding that port alone is not going to be enough to
enable l2 discovery. You would need to configure docker to pass broadcast
traffic to and from that port. I'm looking for any way to do that in bridge
mode now but I can't find any way of doing that outside of using host mode
or macvlan

**Comment by LexxM3** [comment]
Well, for what it is worth, I can 100% confirm that Synology Docker default installation fails without 10001 configured and works with 10001.  I have gone through the process twice from scratch with identical results above (once in Mar 2021 when this issue was first submitted, and second time a few days ago once I decided to actually commit to UniFi).  It is accurate that it is not sufficient, however.  Opening Synology firewall 10001 is required.  As well, configuring the UniFi Controller Host for Inform to a DNS name or IP address visible to the devices to be adopted is also required.

**Comment by jacobalberty** [comment]
I can merge it when I get back home. but as is there's some other
undocumented magic going on there that's making it work. I've tested this
many times. There's at least one previous issue where it was brought up and
found my to be the issue but I tested it at the time of working on that
users problem as well and couldn't coax it to adopt regardless of port
10001 being forwarded

**Comment by LexxM3** [comment]
Ok.  I am very pro doing things most *right*, as long as that doesn't interfere with it *working*.  I am happy to try to test ideas for what is * more right* as much as I can, although at this point this would require setting up separate (from the deployed) UniFi controller instance and network (which I am willing to do within limits).

**Comment by jacobalberty** [comment]
Like I say I'll merge it. It wasn't ignored just fell into low priority at
the time. Because it has been tested on my setup before and not found to
fix layer 2 adoption. And hadn't ever been implemented before because it
never was the source of an issue for someone.  I'm almost done here then
headed back home to merge.

**Comment by LexxM3** [comment]
I think I am most offended by a bot arbitrarily closing the issue with no investigation, not the prioritization.

**Comment by jacobalberty** [comment]
Bots new it's helping me get the old issues cleared so I can get them
reprioritized. It did a good job bringing attention back to it for us to
discuss though
