### ISSUE TITLE
5.4.18

### ISSUE THREAD

**Issue by ahiguero** [jacobalberty/unifi-docker#43]
Hello Jacob

can you make the container for 5.4.18?

**Comment by jacobalberty** [comment]
@ahiguero  I've been trying to decide on the best policy for dealing with stable candidates, I don't want to put them into the 'latest' tag on docker hub yet but at the same time they definitely should be available to test. I'll go ahead and make a tag for this as 5.4.18-sc though give me a minute.

**Comment by jacobalberty** [comment]
5.4.18-sc is tagged out in  16af28a

**Comment by ahiguero** [comment]
thanks buddy... another question how do i build my own for example rather
than waiting for the new deployment form your end how can i get the latest
stable build. i am guessing that i need to edit the docker file right to
download the right data

**Comment by jacobalberty** [comment]
Are you using docker-compose to manage your containers?

**Comment by ahiguero** [comment]
I am using a NAS (QNAP) to host and run my containers. it has something
called docker container station on which you download your containers from
a docker repository, and configure its options (environment, network and
volumes.

for your  container i would have to get the code downloaded somehow and
then do the necessary editing to update the options to the latest package.
that what i think i need to do, i guess.

**Comment by jacobalberty** [comment]
Here's how I do it for testing the lates 5.5.x candidates on my home server

I clone the repository
```git clone https://github.com/jacobalberty/unifi-docker.git```

I then edit my docker-compose.yml and instead of using ```image: jacobalberty/unifi:testing``` I use ```build: unifi-docker```

I then go into the unifi-docker and do ```git checkout testing``` (if you want to use 5.4.x then stay on the master branch) and edit Dockerfile, edit the ```ENV PKGURL=``` line to point to the stable candidate debian package.

Just an note: effectively testing and master are the same right now, they simply have a different PKGURL, in the future though if the testing branch gets different dependency requirements you'll want to be sure you are in the correct branch, so it's a good habit to be in from the beginning.

**Comment by jacobalberty** [comment]
Just saw your comment saying you use QNAP, not 100% sure how to do it with qnap, can you point qnap to a github project instead of using docker hub?

**Comment by ahiguero** [comment]
i have homework to do :) thanks for the tips Jacob

**Comment by ahiguero** [comment]
i wll check that
