### ISSUE TITLE
latest still pointing to erroneous 6.1.71

### ISSUE THREAD

**Issue by mkrecek234** [jacobalberty/unifi-docker#431]
Hi Jacob,
the latest branch still points to 6.1.71 (contrary to what the description says) - as I am running the docker image on Synology, this will result in errors and I am not able to run the package.

Thank you for fixing this

**Comment by jacobalberty** [comment]
`latest` should be pointing to 6.1.x as that's the current stable, i noticed there was a subsection in the readme.md that erroniously said it points to 6.0.x, for 6.0.x you want the `6.0` tag. the docker hub readme was out of sync due to the move to using a build service instead of building on the docker hub directly. I've now synchronized it with the hub.  the 6.2.x stuff appears to still be in rc stage but `6.2.17-rc` points to that if you're looking for 6.2.x
