### ISSUE TITLE
UniFi Controller startup failed - jacobalberty/unifi:latest (2021-05-14)

### ISSUE THREAD

**Issue by abeggled** [jacobalberty/unifi-docker#442]
UniFi Controller startup failed
We do not support upgrading from 6.2.23.

This message appears by accessing to controller website.

The only logentry is:
2021-05-13 22:38:48 | stdout | 2021-05-13 22:38:48,365 main ERROR Unable to locate appender "InMemoryAppender" for logger config "root"
2021-05-13 22:38:47 | stdout | 2021-05-13 22:38:47,544 main ERROR Error processing element InMemoryAppender ([Appenders: null]): CLASS_NOT_FOUND

possible linked to issue #436

**Comment by jacobalberty** [comment]
Unifi 6.2.23 was [pulled by ubiquiti](https://community.ui.com/releases/UniFi-Network-Application-6-2-23/df89533b-184a-4fb7-b2c6-9f894b82df27#comment/ec904582-7f17-4120-800b-711ee81c306c) because it would not properly upgrade for too many people. they pulled it after it was deployed so when I removed it from the docker hub some people had already successfully upgraded. migrate to the `jacobalberty/unifi:6.2` tag in the meantime until a new stable 6.2.x is released. the `latest` tag has been reverted back to 6.1.71

**Comment by abeggled** [comment]
Thanks for the fast response.  Using the `jacobalberty/unifi:6.2` tag did the trick in my situation.

**Comment by themaninspain** [comment]
This also worked for me

**Comment by apollo40** [comment]
Yeah unifi:6.2 fixed it for me too
