### ISSUE TITLE
Not start on Qnap TS-431P3-4G (CPU: 4x ARM Cortex-A15)

### ISSUE THREAD

**Issue by Rickyc81** [jacobalberty/unifi-docker#447]
### Host operating system

QTS - 

### What tag are you using

Stable

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

Installing app from "Container Station"

Note: A screenshot of your configuration page if using a gui is acceptable

### Noting, and server,log  -> "DBServer - Stopped"

![Cattura](https://user-images.githubusercontent.com/4402040/119532282-0826e980-bd85-11eb-86ec-7eae913c3abd.PNG)

Thanks!!

**Comment by frischerfritz** [comment]
I have the same Issue on a TS-231P3. After reading some posts, I concluded: It won't work. The reason lies the ARM 32bit CPU we have in our machines. The latest build of a mongodb for that architecture is from 2019 and version 3.2. Unifi Controller requires 3.6 though. 3.6 has only support for ARM64bit. 

Currently, I don't see any possibility to run the entire stack on those devices... 

However, If someone knows a trick - let us know...

**Comment by Rickyc81** [comment]
https://github.com/jacobalberty/unifi-docker/blob/master/pre_build/armhf/mongodb.sh
This not work because it seem that mongodb 3.2 and core missing dependencies that have been deleted from the linux repo
