### ISSUE TITLE
Containers running out of memory

### ISSUE THREAD

**Issue by boyke** [jacobalberty/unifi-docker#466]
We have two docker host nodes running on CentOS 7 and Docker 17. The problem is that after a while the whole system is running out of memory. When we check which processes use swap space this are java and mongod.

First docker host has 8GB RAM total for two UniFi containers, one on 5.14 and the other 6.2. This one runs out every couple of days since i installed the second container.

Second node has 24GB RAM total for four UniFi containers: 5.9, 5.14 and two 6.2. This one runs out every couple of weeks and it became worse since i installed the two 6.x containers.

I think it is a 6.x problem but maybe in combination with running multiple images on the same host.

**Comment by anthonyloukinas** [comment]
Have you tried putting memory limits on your containers? https://docs.docker.com/config/containers/resource_constraints/#limit-a-containers-access-to-memory

**Comment by cratoo** [comment]
Did any of you try to configure the MongoDB [wiredTigerCacheSize](https://community.ui.com/questions/NOTICE-UniFi-Controller-Memory-Usage-5-6-20/228907d2-8d30-42a0-b97c-b14ef9767edb#answer/d8168a71-acbd-49ed-b420-e77a324be542)? It basically means configuring a memlimit for mongo within the container, which otherwise just uses 50% of the host memory.
For me this finally fixed the memory issue and the container with the controller AND mongodb is running with 800MB perfectly fine, without requiring restarts
