### ISSUE TITLE
Ver. 6.5.55 Unable to access controller from Web. Also Unable to load /usr/lib/unifi/data/system.properties

### ISSUE THREAD

**Issue by MonsieurTIsecurite** [jacobalberty/unifi-docker#505]
### Operating system

Synology DSM 7.0.1-42218 / Docker 20.10.3-1239

### UniFi Tag

V6.5.55

### Docker run

I don't know

### Bug description

Was using version 6.2.26 on Docker  in my Synology. All works fine.

Decide to Upgrade to new image 6.5.55 and Unable to access controller from regular Web link.
Log says : Unable to load properties, 
I tried with or without my mount directory holding my data as backup ie:  "My Folder/unifi" to "/var/lib/unifi" with RW permissions.
Same results... 
Ayn clues... ?

************ Docker LOG *******************
<docker-entrypoint> Starting unifi controller service.
<docker-entrypoint> WARNING: Running UniFi in insecure (root) mode
<docker-entrypoint> WARN Unable to load properties from '/usr/lib/unifi/data/system.properties' - /usr/lib/unifi/data/system.properties (No such file or directory)
************ Docker LOG *******************

**Comment by jacobalberty** [comment]
the `/usr/lib/unifi/data/system.properties` is a red herring error message it's safe to ignore, it will be created when it's needed.

Your volumes don't look quite right though. It should be in `/unifi` not in `/var/lib`. I believe you want to map your existing folder to `/unifi/data` when moving from `/var/lib/unifi` but i would need to see the directory contents of what you have mapped to `/var/lib/unifi` first to confirm. 

Now even without addressing that it should still at least start and give you the new installation screen. What might help for diagnostics is map a folder to /unifi/log/log and post the contents of server.log (or at least any error messages)

**Comment by jakobon** [comment]
I am setting up UniFi Controller for the first time on a QNAP NAS, and also received this error.

On the host I was mapping this path "`/share/CACHEDEV1_DATA/Virtualize/Containers/appdata/unifi`" to this mount point "`/var/lib/unifi`" with RW permissions.

From the error I concluded that the container is setup to expect the persistent config files to be in the `/usr/` path ... (I honestly don't know much about Linux filesystems).

So I basically changed the `--volume` parameter in the `docker run` from "`/var/lib/unifi`" to "`/usr/lib/unifi`"

My current docker run is:
`docker run --name UnifiControl --user=unifi --init --restart=unless-stopped --memory=512m --cpu-quota 50000 --publish 8480:8080 --publish 8443:8443 --publish 3478:3478/udp --env TZ=Europe/Copenhagen --env RUNAS_UID0=false --env UNIFI_UID=999 --env UNIFI_GID=999 --volume=/share/CACHEDEV1_DATA/Virtualize/Containers/appdata/unifi:/usr/lib/unifi:rw jacobalberty/unifi`

Please note, that the "**`/Virtualize/Containers/appdata/`**" part I have created myself, to store configuration for different containers. I also had to change the mapping of the 8080 port as it was already in use.

I don't know the file structure on a Synology, but you just need to find the host path that would correspond to "**`/share/CACHEDEV1_DATA/`**"

But the error was fixed, and the container is created - unfortunately it won't run due to a "Missing an included hotfix" error, but that is another matter.
