### ISSUE TITLE
Running in vSphere Integrated Containers?

### ISSUE THREAD

**Issue by volumen1** [jacobalberty/unifi-docker#53]
I'm having issues running this in vSphere Integrated Containers but it can certainly be user error.  This is a lab environment that I built yesterday and yesterday was also the first time I ever typed "docker" into my CLI so noob-level is quite high.  Here are the steps I took to create the environment:

**Create the VCH**
.\vic-machine-windows.exe create --name unifi --target ESX-server-IP --user root --password "ESXrootpassword" --no-tlsverify --force --image-store "ESX-Datastore-name" --volume-store ESX-Datastore-name/docker-volume-folder:default --dns-server 10.0.0.10 --public-network-ip 10.0.0.20/24 --public-network-gateway 10.0.0.1

This appears to correctly build the virtual container host.  I can query it using the docker client in a shell:

**$ docker -H 10.0.0.20:2376 --tls info**
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: v1.1.1-10711-56a309f
Storage Driver: vSphere Integrated Containers v1.1.1-10711-56a309f Backend Engine
VolumeStores: default
vSphere Integrated Containers v1.1.1-10711-56a309f Backend Engine: RUNNING
 VCH CPU limit: 3679 MHz
 VCH memory limit: 27.93 GiB
 VCH CPU usage: 58 MHz
 VCH memory usage: 4.898 GiB
 VMware Product: VMware ESXi
 VMware OS: vmnix-x86
 VMware OS version: 6.5.0
Plugins:
 Volume: vsphere
 Network: bridge
Swarm: inactive
Operating System: vmnix-x86
OSType: vmnix-x86
Architecture: x86_64
CPUs: 3679
Total Memory: 27.93GiB
ID: vSphere Integrated Containers
Docker Root Dir:
Debug Mode (client): false
Debug Mode (server): false
Registry: registry-1.docker.io
Experimental: false
Live Restore Enabled: false

When I attempt to run unifi-docker, though it appears to hang after "Starting unifi controller service" as seen here:
**$ docker -H 10.0.0.20:2376 --tls run --rm -p 8080:8080 -p 8443:8443 -p 3478:3478 -p 10001:10001 -e TZ='America/Denver' -v /var/lib/unifi -v /var/log/unifi --name unifi jacobalberty/unifi:stable**
Unable to find image 'jacobalberty/unifi:stable' locally
Pulling from jacobalberty/unifi
5233d9aed181: Pull complete
a3ed95caeb02: Pull complete
2e02715fac5e: Pull complete
78a9ca0f090f: Pull complete
3142747da002: Pull complete
8f15781934fa: Pull complete
b9ffd3cc8d63: Pull complete
4fcde711a5af: Pull complete
b13b02c3b14b: Pull complete
0720fe1df3cd: Pull complete
de35a6c93f7b: Pull complete
Digest: sha256:d7bcce256790e59d140105cee309667dfe961ed5e1e98d4272a2eb6ee03d5a99
Status: Downloaded newer image for jacobalberty/unifi:stable
Starting unifi controller service.

A docker ps shows this:
**$ docker -H 10.0.0.20:2376 --tls ps**
CONTAINER ID        IMAGE                       COMMAND                  CREATED                  STATUS              PORTS                                                                                                                      NAMES
27cd00abfcd9        jacobalberty/unifi:stable   "/usr/bin/dumb-ini..."   Less than a second ago   Up 2 hours          10.0.0.20:3478->3478/tcp, 10.0.0.20:8080->8080/tcp, 10.0.0.20:8443->8443/tcp, 10.0.0.20:10001->10001/tcp   unifi

Hitting http://10.0.0.20:8080 in a browser appears to connect, but then I'm stuck at "Waiting for 10.0.0.20..." 

Using this same basic method for VCH creation and docker deployment for a simple "hello world" webserver works fine, so I think the basic method I'm using is sound but I'm probably just missing a detail somewhere?  Any pointers on where to look or any information I can provide to better illuminate this?

**Comment by phroggster** [comment]
It may or may not be something, but ports 3478 and 10001 should be UDP instead of TCP.

**Comment by volumen1** [comment]
Oh, that's interesting.  I didn't realize you could append /udp to the port flag argument to specify udp.  I'll recreate the environment and give that a whirl.  Thanks for the idea!

**Comment by volumen1** [comment]
Well crud.
docker: Error response from daemon: Server error from portlayer: error mapping ports: port 10001 is not available.
ERRO[0074] error getting events from daemon: net/http: request canceled

And if I just specify 3478 as udp and leave 10001 as tcp I get this:
docker: Error response from daemon: Server error from portlayer: error mapping ports: port 3478 is not available.
ERRO[0003] error getting events from daemon: net/http: request canceled

Maybe this is an issue with VCH and udp ports?  I'll chase that angle down.

**Comment by jacobalberty** [comment]
@volumen1 when you recreated with /udp did you delete the old container? that could explain the error. Mapping those ports shouldn't matter though. Try skipping port 8080 and access http://10.0.0.20:8443 port 8080 is just gonna redirect there anyway.

**Comment by volumen1** [comment]
I did delete the container, but the real issue appears to be that I'm unable to create any container with UDP ports mapped to my VCH.  This might be a limitation of vSphere Integrated Containers or maybe I'm missing something with my setup.  Instead, I created a new Ubuntu docker host VM and I'm using it instead.  It's working a treat!

**Comment by jcberthon** [comment]
Just in case you have the wrong syntax for the udp thing:

    $ docker -H 10.0.0.20:2376 --tls run --rm -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='America/Denver' -v /var/lib/unifi -v /var/log/unifi --name unifi jacobalberty/unifi:stable

But note that the UDP ports are optional.

3478 is for the STUN service (NAT traversal, etc.), I'm not sure what's the use here really. The controller works fine for me without that port mapped. But I only have a UAP and USW.

10001 is for Unifi Discovery. Actually I've set up a L3 discovery and discovery works perfectly fine without mapping that port as well.

Finally going back to your initial problem, I think you miss the `--init` flag. So if I remove the 2 optional ports, here is the command:

    $ docker -H 10.0.0.20:2376 --tls run --rm -p 8080:8080 -p 8443:8443 --init -e TZ='America/Denver' -v /var/lib/unifi -v /var/log/unifi --name unifi jacobalberty/unifi:stable

**Comment by volumen1** [comment]
That's interesting.  I'm currently running it on a Ubuntu docker host (I sort of gave up on vSphere Integrated Containers) but my command line on the Ubuntu host didn't  have the --init piece in there.  It looked like this:

docker run -d  --net=host --restart always -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='America/Denver' -v /data/unifi/data:/var/lib/unifi -v /data/unifi/logs:/var/log/unifi --name unifi jacobalberty/unifi:stable

**Comment by jacobalberty** [comment]
> 10001 is for Unifi Discovery. Actually I've set up a L3 discovery and discovery works perfectly fine without mapping that port as well.

I don't believe port 10001 is relevant to this setup, I believe it is only used for layer 2 discovery. However I can't find official documentation directly confirming 10001 does nothing for layer 3 adoption, so I added it to the list of mapped ports.

> my command line on the Ubuntu host didn't have the --init piece in there.

the --init piece is recent. I'm trying to clean up the docker files to prep for arm compatibility and dumb-init isn't available on arm, docker however added a --init parameter to handle process reaping AFTER dumb-init was added to the image. I opted to remove dumb-init and update the documentation to recommend using --init.

Functionality for most people should be the same with or without --init, process reaping is for zombie processes, in theory if all is going well you shouldn't see any zombie processes. You should include --init, however for the issues you had with vSphere --init should not be relevant.

**Comment by jcberthon** [comment]
Correct 10001 is only for L2, that what I clumsily meant. And I agree I do not think it is relevant here, hence my last paragraph "going back to your initial problem".

I do recall that you had the dumb-init (btw it exists [for ARM, I've installed it using pip once](https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/merge_requests/555#note_27632366)) and you're right, I overlook the `ps` output, the image used was based on it. So there would have been no need for the `--init` flag.

Note to @volumen1  that if you use `--net=host` then you do not need to perform any port mapping. The port mapping is there to define "port forwarding" rules between your LAN and the "isolated" network in which your container is. However, if you use `--net=host` you are giving your container your host network (access to all devices), so when the container bind port 8443, it is bound on your network interface on your LAN, so the port mapping becomes irrelevant. In terms of security, it is not the best approach because the container has now full access to your NIC, but it also slightly decrease the latency because it is directly connected to your device.

**Comment by jacobalberty** [comment]
In aware dumb-init is available for arm, but if I put it in the unifi image
its one more difference between x64 and arm, from what I've read the plan
for multi architecture on the hub is to have the same dockerfile able to
build any architecture, moving away from dumb-init prepares for that
eventuality.


There is a third option beyond net=host and port mapping btw. Macvlan. I
don't know how it works on vspheres but I do believe I put instructions for
docker cli and docker-compose in readme.md. macvlan can give you the easy
setup with l2 adoption but with a little more isolation than net=host. The
only additional exposure would be the possibility of mongodb listening on a
public port. I haven't looked at unifi close enough to see if mongodb binds
to the lo interface or the public one.

On Aug 25, 2017 3:44 PM, "Jean-Christophe" <notifications@github.com> wrote:

Correct 10001 is only for L2, that what I clumsily meant. And I agree I do
not think it is relevant here, hence my last paragraph "going back to your
initial problem".

I do recall that you had the dumb-init (btw it exists for ARM, I've
installed it using pip once
<https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/merge_requests/555#note_27632366>)
and you're right, I overlook the ps output, the image used was based on it.
So there would have been no need for the --init flag.

Note to @volumen1 <https://github.com/volumen1> that if you use --net=host
then you do not need to perform any port mapping. The port mapping is there
to define "port forwarding" rules between your LAN and the "isolated"
network in which your container is. However, if you use --net=host you are
giving your container your host network (access to all devices), so when
the container bind port 8443, it is bound on your network interface on your
LAN, so the port mapping becomes irrelevant. In terms of security, it is
not the best approach because the container has now full access to your
NIC, but it also slightly decrease the latency because it is directly
connected to your device.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/jacobalberty/unifi-docker/issues/53#issuecomment-325030104>,
or mute the thread
