### ISSUE TITLE
USG Json file

### ISSUE THREAD

**Issue by smerchant** [jacobalberty/unifi-docker#56]
I can't seem to find where to upload the JSON files. I am using docker with synology.

**Comment by jacobalberty** [comment]
Did you map a volume to /var/lib/unifi? if so that is where the json files would go that volume subdirectory `data/sites/default` I believe. See [more info here](https://help.ubnt.com/hc/en-us/articles/215458888-UniFi-How-to-further-customize-USG-configuration-with-config-gateway-json) for that articles purposes the /var/lib/unifi volume is `<unifi_base>`.

**Comment by smerchant** [comment]
Jacob, I figured it out. I was expecting a json file at the location, and I
was wrong. I had to create one. Thank you for your prompt response.
