### ISSUE TITLE
Failure when trying to add key from hkp:// server

### ISSUE THREAD

**Issue by MartB** [jacobalberty/unifi-docker#571]
https://github.com/jacobalberty/unifi-docker/blob/059ca656ced6c6de8f11b46528d7bfcc97f12591/docker-build.sh#L44

Is there any particular reason why this is not using `addKey`?

**Comment by xiaoyaowx** [comment]
replace with
wget -O /etc/apt/trusted.gpg.d/unifi-repo.gpg https://dl.ui.com/unifi/unifi-repo.gpg

**Comment by jacobalberty** [comment]
I think just because keyserver.ubuntu.com hadn't had an issue so it had not come up.  I believe the only ones working from addKey are the ubuntu ones and pgp.mit.edu right now, the sks infrastructure was all torn down. Those actually need to be removed from addKey, might not be a bad idea to move that line onto addKey when i do
