### ISSUE TITLE
beta - Java 17 required for 7.5.165

### ISSUE THREAD

**Issue by nibblerrick** [jacobalberty/unifi-docker#673]
### Operating system

Debian bullseye, docker beta image

### UniFi Tag

EA

### Docker run

docker run -d --init --restart=unless-stopped -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -e TZ='Europe/Berlin' -v unifi-data:/unifi --name unifi -e https://dl.ui.com/unifi/7.5.165-9316de8cde/unifi_sysvinit_all.deb jacobalberty/unifi:beta

### Bug description

Controller won't start and errors out because of incompatible java version.

Would be nice if the beta image could get some love again.
Probably changing the java version should do the trick already, if AFAIK the beta image uses bullseye and the package openjdk-17-[jre-headless](https://packages.debian.org/bullseye/openjdk-17-jre-headless) is available there.

Thanks in advance!

**Comment by jcostom** [comment]
I forked and created a working proof-of-concept supporting v7.5. There's a delicate line to walk here - the base image has to be Ubuntu 20.04 (aka Focal).

Focal has Java 17 and MongoDB 3.6. The more recent LTS, 22.04/Jammy has Java 17, but no Mongo packages at all. You can of course add the mongodb.org repo for Jammy to the image, but the furthest back they support is v4.x, which reportedly works, though isn't supported by Ubiquiti.

There seems to be a minor thing introduced by Java 17 here, where the controller tosses its cookies because of a permissions problem with java.time. I found a [workaround](https://stackoverflow.com/questions/70412805/what-does-this-error-mean-java-lang-reflect-inaccessibleobjectexception-unable) though and added that to the JVM options in my proof-of-concept.

The differences here are not massive. It looks possible to support v7.5 without a ton of pain. [Here's the diff between where I landed and the current release](https://github.com/jacobalberty/unifi-docker/compare/master...jcostom:unifi-docker:master).

IMHO, this whole thing would get a LOT easier if Ubiquiti would support MongoDB 6.

**Comment by it-can** [comment]
@jacobalberty any news on this?

**Comment by jcostom** [comment]
FYI - I just updated to 7.5.174 and everything works in my testing. That link I posted above still goes to the diff's between this repo and my fork. I'm happy to file a pull request once 7.5 goes GA if folks would like.

**Comment by skynet01** [comment]
Any ideas  @jacobalberty when this can be added to the official release? Would love to get 7.5 going :)  Thanks again for all your hard work

**Comment by it-can** [comment]
> FYI - I just updated to 7.5.174 and everything works in my testing. That link I posted above still goes to the diff's between this repo and my fork. I'm happy to file a pull request once 7.5 goes GA if folks would like.

yeah that would be nice! i see that https://community.ui.com/releases/UniFi-Network-Application-7-5-174/d05b091f-f00c-4ebb-8f42-b77e0adac78b  is a RC now

**Comment by skynet01** [comment]
> FYI - I just updated to 7.5.174 and everything works in my testing. That link I posted above still goes to the diff's between this repo and my fork. I'm happy to file a pull request once 7.5 goes GA if folks would like.

Now that it's official, want to do that pull request now :)

**Comment by jcostom** [comment]
> > FYI - I just updated to 7.5.174 and everything works in my testing. That link I posted above still goes to the diff's between this repo and my fork. I'm happy to file a pull request once 7.5 goes GA if folks would like.
> 
> Now that it's official, want to do that pull request now :)

I'm testing. I don't expect any problems, but wanted to check first.

**Comment by jacobalberty** [comment]
Taking a look at the pr right now, though its currently failing the build though, my guess is its failing on the 32 bit arm support. iirc 20.04 does not have any path to supporting arm32 which is why we stayed on 18.04 for so long. It might be worth bumping mongodb soon, the release notes for 7.5.x specify `Require MongoDB 3.6 or newer. This also drops support for 32-bit systems.` so it looks like its time to drop arm 32 entirely. Maybe bump mongodb to a newer version and go with the latest ubuntu lts (22.04)

**Comment by jcostom** [comment]
I suspect you're correct. I don't have anything arm32 handy to test with, unfortunately. I didn't catch the mongodb 3.6 or newer line either. It would be nice if it worked on 6.x, which would enable going to the Ubuntu Jammy base image. I'll see if I get some time to try that out this week.

**Comment by jcostom** [comment]
Taking a peek at the .deb file, the dependencies show...

```
Depends: binutils, coreutils, adduser, libcap2, curl,
  mongodb-server (>= 1:3.6.0) | mongodb-10gen (>= 3.6.0) | mongodb-org-server (>= 3.6.0),
  mongodb-server (<< 1:5.0.0) | mongodb-10gen (<< 5.0.0) | mongodb-org-server (<< 5.0.0),
  openjdk-17-jre-headless, logrotate
```

If I'm reading that right, 3.6 - 4.4.24 would now be acceptable versions. The earliest version available for Ubuntu Jammy in their repositories seems to be 5.x, so that still leaves us stuck on Focal/20.04. Definitely progress though!

**Comment by nibblerrick** [comment]
Thanks!
The beta-image isn't updated so far, or can the pkgurl-parameter also used with the master image?

**Comment by skialpine** [comment]
This is in the latest image, not beta. The release is GA.

**Comment by nibblerrick** [comment]
Saw that, but my initial question/report was for the beta image, so question is what's with the beta image :-)
New EA from unifi will come sooner or later.
