### ISSUE TITLE
Update to 7.5.187

### ISSUE THREAD

**Issue by dajappie** [jacobalberty/unifi-docker#696]
Version 7.5.187 is official now at https://community.ui.com/releases/UniFi-Network-Application-7-5-187/408b64c5-a485-4a37-843c-31e87140be64. Is it possible to provide an updated image?

**Comment by boyke** [comment]
Yes please!

**Comment by timbuktu234** [comment]
Second @dajappie Version 7.5.187 is official!

**Comment by maverick1317** [comment]
The new version is already downloadable?

**Comment by dajappie** [comment]
> The new version is already downloadable?

See link above, check under Download Links

**Comment by explicitworkload** [comment]
Second this. Looking for 187 as well. ;)

**Comment by cletusw** [comment]
Looks like creating a PR to upgrade probably isn't complicated (e.g. https://github.com/jacobalberty/unifi-docker/pull/685/files ), but I don't have good enough docker chops to know how I'd test a PR like that.

**Comment by dajappie** [comment]
Pull request is actually already open for a bit now at #694 and actively worked on today but seems to be awaiting approval by @jacobalberty

**Comment by hesne** [comment]
Any news? We need this update!

**Comment by wufei0** [comment]
update?

**Comment by explicitworkload** [comment]
Since there's no update for 3 weeks, I have moved it over to linuxserver's unifi container instead. There isn't any impact to my persistent volumes. It's relatively easy.

**Comment by hesne** [comment]
Maybe someone can build the container with the PR #694 ? Would be helpful to wait for @jacobalberty

**Comment by cfmk** [comment]
> linuxserver's unifi

You just changed the docker compose files and kept all the data??

**Comment by orpheus1120** [comment]
> Since there's no update for 3 weeks, I have moved it over to linuxserver's unifi container instead. There isn't any impact to my persistent volumes. It's relatively easy.

Same here.

**Comment by orpheus1120** [comment]
> > linuxserver's unifi
> 
> 
> 
> You just changed the docker compose files and kept all the data?? 

Back up your configuration then restore when you have the linuxserver's container up and running.

**Comment by mooglestiltzkin** [comment]
**Published: October 23, 2023

Instances of UniFi Network Application that (i) are run on a UniFi Gateway Console, and (ii) are versions 7.5.176. and earlier, implement device adoption with improper access control logic, creating a risk of access to device configuration information by a malicious actor with preexisting access to the network.

**Mitigation:

Update UniFi Network to Version 7.5.187 or later.****

https://community.ui.com/releases/Security-Advisory-Bulletin-036-036/81367bc9-2a64-4435-95dc-bbe482457615


plz we need an update

**Comment by buckaroogeek** [comment]
I hope I do not regret this.

I forked Jacob's repository and built version 7.5.187. Uploaded to Docker hub at https://hub.docker.com/r/buckaroogeek/unifi/tags.

I have this version running on my Synology NAS for a day. Seems to be ok. Please note I do not regularly build with Docker and in fact used a different tool set than Jacob likely uses. I use docker-compose on the Synology to launch the container. The relevant change in the docker-compose.yml file is:

```
...
  unifi:
    image: "buckaroogeek/unifi:v7"
#    image: "jacobalberty/unifi:v7"
    container_name: SageCreek-Unifi-Controller
    hostname: unifi2
    domainname: lan
...
```

I have 4 tags: v7.5.187, v7.5, v7, latest which should cover most users. 

Since my version has a different namespace (buckaroogeek), Jacob's version is still present in the local Docker image repository and readily available to roll back to (but I have not tried to rollback). 

So pending Jacob's return please feel free to try this version.

**Comment by hesne** [comment]
Also forked the repo and build 7.5.187 and 7.0.8.
Running on 50 different controllers. Works great. Docker repo: https://hub.docker.com/r/hesnes/unifi
________________________________
Von: Brad Smith ***@***.***>
Gesendet: Wednesday, November 22, 2023 7:36:06 PM
An: jacobalberty/unifi-docker ***@***.***>
Cc: Henning Eßer ***@***.***>; Comment ***@***.***>
Betreff: Re: [jacobalberty/unifi-docker] Update to 7.5.187 (Issue #696)


I hope I do not regret this.

I forked Jacob's repository and built version 7.5.187. Uploaded to Docker hub at https://hub.docker.com/r/buckaroogeek/unifi/tags.

I have this version running on my Synology NAS for a day. Seems to be ok. Please note I do not regularly build with Docker and in fact used a different tool set than Jacob likely uses. I use docker-compose on the Synology to launch the container. The relevant change in the docker-compose.yml file is:

...
  unifi:
    image: "buckaroogeek/unifi:v7"
#    image: "jacobalberty/unifi:v7"
    container_name: SageCreek-Unifi-Controller
    hostname: unifi2
    domainname: lan
...


I have 4 tags: v7.5.187, v7.5, v7, latest which should cover most users.

Since my version has a different namespace (buckaroogeek), Jacob's version is still present in the local Docker image repository and readily available to roll back to (but I have not tried to rollback).

So pending Jacob's return please feel free to try this version.
