### ISSUE TITLE
Device Firmware not udpating

### ISSUE THREAD

**Issue by dcbell** [jacobalberty/unifi-docker#721]
Is the System > Updates > Device Firmware expected to work? I just updated my image to 8.0.26 from one of the v7 builds previously, and it won't see any new firmware. All my devices are stuck on 6.6 and it seems happy to stay there.

![unifi](https://github.com/jacobalberty/unifi-docker/assets/930515/3a311095-0e4d-4980-a352-0cdac42f4f32)

**Comment by JayKuswahey** [comment]
Hi,

What makes you think there's new firmwares available? There's nothing new mentioned over at [their website](https://ui.com/download/releases/firmware) since December? I'm pretty sure they do not match the firmware versions with the controller version.

Just to be sure: I don't have any updates available either on my 7.5 deployment :) 

![image](https://github.com/jacobalberty/unifi-docker/assets/70522034/b3ccd316-a26a-494e-ac6a-afdecdd62c7e)

**Comment by dcbell** [comment]
> Hi,
> 
> What makes you say there's new firmwares available? There's nothing new mentioned over at [their website](https://ui.com/download/releases/firmware) since December? I'm pretty sure they do not match the firmware versions with the controller version.
> 
> Just to be sure: I don't have any updates available either on my 7.5 deployment :)

I completely misread the firmware download page on the Unifi site. Sorry about the confusion.
