### ISSUE TITLE
How do I download the package for my Qnap nas?

### ISSUE THREAD

**Issue by stano-vittorio** [jacobalberty/unifi-docker#728]
Hello everyone! I can't figure out how to download the file package to install this latest version on my Qnap NAS.

**Comment by Gamertech** [comment]
Follow [this](https://www.smarthomebeginner.com/qnap-docker-compose-guide-2023/) to get Docker installed, then follow [this](https://hub.docker.com/r/jacobalberty/unifi) to configure the Docker image

**Comment by CommanderCaveman** [comment]
I can download the Jacobalberty/unifi but I am unable to get it to run properly. I have created folders in where I believe are the right places but even then there is something not working right. I get the following error message within the Container Station Logs section.
[2024-04-05 20:58:46,428] <docker-entrypoint> Starting unifi controller service.
[2024-04-05 20:58:46,436] <docker-entrypoint> WARNING: Running UniFi in insecure (root) mode
WARN Unable to load properties from '/usr/lib/unifi/data/system.properties' - /usr/lib/unifi/data/system.properties (No such file or directory)
The folders exist DataVol1/Container/container-station-data/application/unifi and under container-station-data/lib/unifi. The only change to the folder structure I can I dentify is under the docker/volumes path.
I am running a fully updated QNAP TS-451, I get teh error server not found when I follow the link https://docker-host-address:8443/.

From the instructions mentioned in the post above I dont need to download and replace the docker installation, the only delta I have is that I have to have a fixed IP address due to not being able to enable the QNAP DCHP service which causes a conflict with my router and Service provider.
Any advice gratefully recieved.

**Comment by Gamertech** [comment]
Looks like a permission issue. Need to ensure the container is given the right perms to access the directories it needs.

No idea how to do that on QNAP. Always avoided them due to their abysmal security.

**Comment by Sysadminfromhell** [comment]
Help needed here? I`m running it off my QNAP NAS.
