### ISSUE TITLE
New Synology setup, devices stuck in "Adoption/Disconnected" loop

### ISSUE THREAD

**Issue by millercentral** [jacobalberty/unifi-docker#97]
### Host operating system

Synology DSM 6.1

### What tag are you using

latest

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

docker run -d --init \
  -p 8080:8080 \
  -p 8443:8443 \
  -p 3478:3478/udp \
  -p 10001:10001/udp \
  -e TZ='America/Los_Angeles' \
  -e RUNAS_UID0=false \
  -e BIND_PRIV=false \
  -e UNIFI_UID=1026 -e UNIFI_GID=100 \
  -v "/volume1/docker/unifi:/unifi" \
  --name unifi jacobalberty/unifi

Note: A screenshot of your configuration page if using a gui is acceptable

### What do you expect to happen?

created a backup from the original Unifi Controller instance on the network (which was running 5.4.18), and stopped it. Started the new container on the new Synology, and loaded the backup on the initial setup page. UI refreshed, showing my switch and 3 APs, all with "Adopting" in the status. Expected this to update to "Connected".

### What actually happens?

Instead of updating to "Connected" after about 30 seconds each of the devices went to "Disconnected" and then back to "Adopting". This repeats endlessly. If I stop this instance of the Unifi Controller and restart the original one, the devices show active and connected there. 

###  Other information:
Log files:
[mongod.log](https://github.com/jacobalberty/unifi-docker/files/1637770/mongod.log)
[server.log](https://github.com/jacobalberty/unifi-docker/files/1637771/server.log)

Synology 1817+, no additional firewall in place. Any idea what could be going wrong?

Thanks.

**Comment by jacobalberty** [comment]
Did the ip address of your hardware change with the new synology? If so that's the most likely cause of the issue. You have two options. Either have configure it to get the same ip address the old one had, or log in to each ap via ssh and issue the following commands
```
mca-cli
set-inform ip-address-of-controller:8080/inform
```
If you have local dns control i suggest setting unifi.yourdomain or just unifi to resolve to the controller ip then use `set-inform unifi:8080/inform` and in the future you can update that dns record to point to the new controller ip so no need to log in to each ap.

**Comment by millercentral** [comment]
That was it. Thank you very much for the assist.
